[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://upbeat-flow-production.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
