// ═══════════════════════════════════════════════════════════════════
// PANEL INFO DATA REGISTRY
// Maps panel IDs to their descriptions, usage guides, and tips
// ═══════════════════════════════════════════════════════════════════

export interface PanelInfo {
    titleKey: string;
    descriptionKey: string;
    usageKey: string;
    tipsKey: string;
    dataPointsKey: string;
    importance: "critical" | "high" | "medium" | "low";
    icon: string; // emoji
}

// Panel info registry - maps panel IDs to i18n keys
export const PANEL_INFO_REGISTRY: Record<string, PanelInfo> = {
    "clear-trend": {
        titleKey: "panelInfo.clearTrend.title",
        descriptionKey: "panelInfo.clearTrend.description",
        usageKey: "panelInfo.clearTrend.usage",
        tipsKey: "panelInfo.clearTrend.tips",
        dataPointsKey: "panelInfo.clearTrend.dataPoints",
        importance: "critical",
        icon: "📊",
    },
    "pulse-panel": {
        titleKey: "panelInfo.pulse.title",
        descriptionKey: "panelInfo.pulse.description",
        usageKey: "panelInfo.pulse.usage",
        tipsKey: "panelInfo.pulse.tips",
        dataPointsKey: "panelInfo.pulse.dataPoints",
        importance: "critical",
        icon: "⚡",
    },
    "pulse-v3": {
        titleKey: "panelInfo.pulseV3.title",
        descriptionKey: "panelInfo.pulseV3.description",
        usageKey: "panelInfo.pulseV3.usage",
        tipsKey: "panelInfo.pulseV3.tips",
        dataPointsKey: "panelInfo.pulseV3.dataPoints",
        importance: "critical",
        icon: "🔥",
    },
    "pulse-ml": {
        titleKey: "panelInfo.pulseMl.title",
        descriptionKey: "panelInfo.pulseMl.description",
        usageKey: "panelInfo.pulseMl.usage",
        tipsKey: "panelInfo.pulseMl.tips",
        dataPointsKey: "panelInfo.pulseMl.dataPoints",
        importance: "critical",
        icon: "🤖",
    },
    "emel-panel": {
        titleKey: "panelInfo.emel.title",
        descriptionKey: "panelInfo.emel.description",
        usageKey: "panelInfo.emel.usage",
        tipsKey: "panelInfo.emel.tips",
        dataPointsKey: "panelInfo.emel.dataPoints",
        importance: "critical",
        icon: "🎯",
    },
    "pattern-engine": {
        titleKey: "panelInfo.patternEngine.title",
        descriptionKey: "panelInfo.patternEngine.description",
        usageKey: "panelInfo.patternEngine.usage",
        tipsKey: "panelInfo.patternEngine.tips",
        dataPointsKey: "panelInfo.patternEngine.dataPoints",
        importance: "high",
        icon: "🔬",
    },
    "sentiment": {
        titleKey: "panelInfo.sentiment.title",
        descriptionKey: "panelInfo.sentiment.description",
        usageKey: "panelInfo.sentiment.usage",
        tipsKey: "panelInfo.sentiment.tips",
        dataPointsKey: "panelInfo.sentiment.dataPoints",
        importance: "high",
        icon: "💭",
    },
    "whale-tracker": {
        titleKey: "panelInfo.whaleTracker.title",
        descriptionKey: "panelInfo.whaleTracker.description",
        usageKey: "panelInfo.whaleTracker.usage",
        tipsKey: "panelInfo.whaleTracker.tips",
        dataPointsKey: "panelInfo.whaleTracker.dataPoints",
        importance: "high",
        icon: "🐋",
    },
    "institutional-data": {
        titleKey: "panelInfo.institutional.title",
        descriptionKey: "panelInfo.institutional.description",
        usageKey: "panelInfo.institutional.usage",
        tipsKey: "panelInfo.institutional.tips",
        dataPointsKey: "panelInfo.institutional.dataPoints",
        importance: "high",
        icon: "🏛️",
    },
    "candlestick-patterns": {
        titleKey: "panelInfo.candlestick.title",
        descriptionKey: "panelInfo.candlestick.description",
        usageKey: "panelInfo.candlestick.usage",
        tipsKey: "panelInfo.candlestick.tips",
        dataPointsKey: "panelInfo.candlestick.dataPoints",
        importance: "high",
        icon: "🕯️",
    },
    "advanced-nasdaq": {
        titleKey: "panelInfo.advancedAnalysis.title",
        descriptionKey: "panelInfo.advancedAnalysis.description",
        usageKey: "panelInfo.advancedAnalysis.usage",
        tipsKey: "panelInfo.advancedAnalysis.tips",
        dataPointsKey: "panelInfo.advancedAnalysis.dataPoints",
        importance: "high",
        icon: "📈",
    },
    "advanced-xauusd": {
        titleKey: "panelInfo.advancedAnalysis.title",
        descriptionKey: "panelInfo.advancedAnalysis.description",
        usageKey: "panelInfo.advancedAnalysis.usage",
        tipsKey: "panelInfo.advancedAnalysis.tips",
        dataPointsKey: "panelInfo.advancedAnalysis.dataPoints",
        importance: "high",
        icon: "📈",
    },
    "strategy-performance": {
        titleKey: "panelInfo.strategyPerformance.title",
        descriptionKey: "panelInfo.strategyPerformance.description",
        usageKey: "panelInfo.strategyPerformance.usage",
        tipsKey: "panelInfo.strategyPerformance.tips",
        dataPointsKey: "panelInfo.strategyPerformance.dataPoints",
        importance: "high",
        icon: "📊",
    },
    "smc-panel": {
        titleKey: "panelInfo.smc.title",
        descriptionKey: "panelInfo.smc.description",
        usageKey: "panelInfo.smc.usage",
        tipsKey: "panelInfo.smc.tips",
        dataPointsKey: "panelInfo.smc.dataPoints",
        importance: "critical",
        icon: "💰",
    },
    "mtf-matrix": {
        titleKey: "panelInfo.mtfMatrix.title",
        descriptionKey: "panelInfo.mtfMatrix.description",
        usageKey: "panelInfo.mtfMatrix.usage",
        tipsKey: "panelInfo.mtfMatrix.tips",
        dataPointsKey: "panelInfo.mtfMatrix.dataPoints",
        importance: "critical",
        icon: "🔄",
    },
    "risk-reward": {
        titleKey: "panelInfo.riskReward.title",
        descriptionKey: "panelInfo.riskReward.description",
        usageKey: "panelInfo.riskReward.usage",
        tipsKey: "panelInfo.riskReward.tips",
        dataPointsKey: "panelInfo.riskReward.dataPoints",
        importance: "critical",
        icon: "⚖️",
    },
    "cot-whale": {
        titleKey: "panelInfo.cotWhale.title",
        descriptionKey: "panelInfo.cotWhale.description",
        usageKey: "panelInfo.cotWhale.usage",
        tipsKey: "panelInfo.cotWhale.tips",
        dataPointsKey: "panelInfo.cotWhale.dataPoints",
        importance: "high",
        icon: "📑",
    },
    "seasonality": {
        titleKey: "panelInfo.seasonality.title",
        descriptionKey: "panelInfo.seasonality.description",
        usageKey: "panelInfo.seasonality.usage",
        tipsKey: "panelInfo.seasonality.tips",
        dataPointsKey: "panelInfo.seasonality.dataPoints",
        importance: "medium",
        icon: "📅",
    },
    "learning-dashboard": {
        titleKey: "panelInfo.learningDashboard.title",
        descriptionKey: "panelInfo.learningDashboard.description",
        usageKey: "panelInfo.learningDashboard.usage",
        tipsKey: "panelInfo.learningDashboard.tips",
        dataPointsKey: "panelInfo.learningDashboard.dataPoints",
        importance: "high",
        icon: "🎓",
    },
    "signal-nasdaq": {
        titleKey: "panelInfo.signalCard.title",
        descriptionKey: "panelInfo.signalCard.description",
        usageKey: "panelInfo.signalCard.usage",
        tipsKey: "panelInfo.signalCard.tips",
        dataPointsKey: "panelInfo.signalCard.dataPoints",
        importance: "critical",
        icon: "📡",
    },
    "signal-xauusd": {
        titleKey: "panelInfo.signalCard.title",
        descriptionKey: "panelInfo.signalCard.description",
        usageKey: "panelInfo.signalCard.usage",
        tipsKey: "panelInfo.signalCard.tips",
        dataPointsKey: "panelInfo.signalCard.dataPoints",
        importance: "critical",
        icon: "📡",
    },
};
